version: '2'

services:
  # cloud_proxy:
  #   restart: always
  #   image: gcr.io/cloudsql-docker/gce-proxy:1.16
  #   command:
  #     /cloud_sql_proxy --instances="leo-dataplatform:us-central1:leo-web-application-development"=tcp:0.0.0.0:5432 --credential_file=/.ssh/leo-dataplatform-fd3d4a9cb675.json
  #   ports:
  #     - "25432:5432"
  #   volumes:
  #     - ./.local:/.ssh
  backend:
    # restart: always
    environment:
      - PORT=5000
      - DATABASE_URI=postgres://leonardo:leonardo@172.16.11.24:35432/dev_leonardo_db
      - GCP_PROJECT_ID=leo-etlplatform
      - GCP_PUBSUB_SUBSCRIPTION=dev_leo_backend_work_task_sub
      - GCP_PUBSUB_CS_CHART_TOPIC=dev_leo_backend_work_task
      - GCP_BQ_TIMEOUT=6000
      - BQ_DATASET=datamart
      - LOGGER_NAME=leo-backend-service
      - LOGGER=application
      - ENABLE_CLOUD_LOGGING=0
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.local/dev-be-leo-etlplatform-ec7a7c9c470c.json
    image: registry.gitlab.com/tpp-leonardo/leo-backend-service/base:latest
    command: >
      ash -c "pip install -r requirements.txt &&
              gunicorn --bind 0.0.0.0:5000 --workers 1 --threads 8 --reload app:app"
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - "5000:5000"
    # depends_on:
    #   - cloud_proxy
  worker:
    # restart: always
    environment:
      - BQ_DATASET_DATAMART_CS=datamart_cs
      - BQ_DATASET_STAGING=staging
      - GCP_DATA_PLATFORM_PROJECT_ID=leo-etlplatform
      - GCP_WEBAPP_PROJECT_ID=leo-dataplatform
      - GCP_WEBAPP_SERVICE_ACCOUNT_KEY_PATH=/app/.local/leo-webapp-qc-6a37a0b04889.json
      - BACKEND_SERVICE_URI=http://backend:5000
      - PORT=5001
      - DATABASE_URI=postgres://leonardo:leonardo@172.16.11.24:35432/dev_leonardo_db
      - GCP_PROJECT_ID=leo-etlplatform
      - GCP_WEBAPP_PUBSUB_VALIDATE_COMPANY_DS_SUBSCRIPTION=dev_company_ds_validation
      - GCP_WEBAPP_PUBSUB_VALIDATE_COMPANY_DS_TOPIC=dev_company_ds
      - GCP_PUBSUB_REQUEST_TOPIC=dev_requests
      - GCP_PUBSUB_SCHEDULE_SUBSCRIPTION=dev_cs_schedule_webplatform
      - GCP_PUBSUB_SCHEDULE_TOPIC=dev_cs_schedule
      - GCP_PUBSUB_SUBSCRIPTION=dev_leo_backend_work_task_sub
      - GCP_PUBSUB_CS_PROGRESS_SUBSCRIPTION=dev_cs_progress_webplatform
      - GCP_PUBSUB_CS_CHART_TOPIC=dev_leo_backend_work_task
      - GCP_PUBSUB_CS_ERROR_SUBSCRIPTION=dev_cs_error_webplatform
      - GCP_PUBSUB_CS_ERROR_TOPIC=dev_cs_error
      - GCP_PUBSUB_COMPANY_DATASOURCE_SUBSCRIPTION=dev_company_datasource_progress_master
      - GCP_PUBSUB_COMPANY_DATASOURCE_TOPIC=dev_company_datasource_progress
      - GCP_PUBSUB_COMPANY_DATASOURCE_ERROR_SUBSCRIPTION=dev_company_datasource_error_master
      - GCP_PUBSUB_COMPANY_DATASOURCE_ERROR_TOPIC=dev_company_datasource_error
      - GCP_PUBSUB_CS_ERROR_DELAY=1
      - GCP_BQ_TIMEOUT=6000
      - BQ_DATASET=datamart
      - LOGGER_NAME=leo-backend-service
      - LOGGER=application
      - ENABLE_CLOUD_LOGGING=0
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.local/dev-be-leo-etlplatform-ec7a7c9c470c.json
      - URL=https://172.16.11.24:8082/api/v1/
      - ADMIN_USERNAME=backendadmin1
      - ADMIN_PASSWORD=a123b321c456
      - SPARKPOST_API_KEY=b8cf47799638f7771ed7768881526820716aadc1
    image: registry.gitlab.com/tpp-leonardo/leo-backend-service/base:latest
    build:
      context: .
      dockerfile: dockerfiles/DockerfileWorker
    command:
      ash -c "pip install -r requirements.txt &&
              mkdir -p /etc/supervisor/conf.d/ &&
              cp worker-supervisord.conf /etc/supervisor/conf.d/supervisord.conf &&
              supervisord -c  /etc/supervisor/conf.d/supervisord.conf"
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - "5001:5001"
    # depends_on:
    #   - cloud_proxy

