# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leo-backend-es-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leo-backend-es-service
  template:
    metadata:
      labels:
        app: leo-backend-es-service
    spec:
      containers:
      - name: leo-backend-es-service
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/cloud-marketplace/google/elasticsearch7:7.10
        # This app listens on port 5000 for web traffic by default.
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"

---
# The hello service provides a load-balancing proxy over the hello-app
# pods. By specifying the type as a 'LoadBalancer', Kubernetes Engine will
# create an external HTTP load balancer.
apiVersion: v1
kind: Service
metadata:
  name: leo-backend-es-service
spec:
  type: LoadBalancer
  selector:
    app: leo-backend-es-service
  ports:
  - port: 80
    targetPort: 5000
