# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leo-backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leo-backend-service
  template:
    metadata:
      labels:
        app: leo-backend-service
    spec:
      containers:
      - name: leo-backend-service-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: us.gcr.io/leo-dataplatform/backend-flask-app
        # This app listens on port 5000 for web traffic by default.
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: DATABASE_URI
            value: "postgres+psycopg2://leonardo:leonardo!@#@127.0.0.1:5432/dev_leonardo_db"
          - name: GCP_DATA_PLATFORM_PROJECT_ID
            value: "leo-etlplatform"
          - name: GCP_PROJECT_ID
            value: "leo-etlplatform"
          # CS Charts env vars
          - name: GCP_PUBSUB_SUBSCRIPTION
            value: "dev_leo_backend_work_task_sub"
          - name: GCP_PUBSUB_CS_CHART_TOPIC
            value: "dev_leo_backend_work_task"
          # CS crawl error status
          - name: GCP_PUBSUB_CS_ERROR_SUBSCRIPTION
            value: "dev_cs_error_webplatform"
          - name: GCP_PUBSUB_CS_ERROR_TOPIC
            value: "dev_cs_error"
          - name: GCP_PUBSUB_CS_ERROR_DELAY
            value: "30"
          # CS crawl progress
          - name: GCP_PUBSUB_CS_PROGRESS_SUBSCRIPTION
            value: "dev_cs_progress_webplatform"
          - name: "GCP_PUBSUB_REQUEST_TOPIC"
            value: "dev_requests"
          # Scheduler
          - name: GCP_PUBSUB_SCHEDULE_SUBSCRIPTION
            value: "dev_cs_schedule_webplatform"
          - name: GCP_PUBSUB_SCHEDULE_TOPIC
            value: "dev_cs_schedule"
          # Validation
          - name: GCP_PUBSUB_VALIDATE_COMPANY_DS_TOPIC
            value: "dev_company_ds_validation"
          - name: GCP_PUBSUB_VALIDATE_COMPANY_DS_SUBSCRIPTION
            value: "dev_company_ds"
          # Global worker delay time
          - name: GCP_BQ_TIMEOUT
            value: "60"
          - name: BQ_DATASET
            value: "datamart"
          - name: BQ_DATA_WAREHOUSE_DATASET
            value: "dwh"
          - name: LOGGER_NAME
            value: "leo-backend-service"
          - name: LOGGER
            value: "application"
          - name: ENABLE_CLOUD_LOGGING
            value: "1"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/app/etc/google/auth/backend-service_account.json"
          - name: CASE_STUDY_NLP_INDEX_PREFIX
            value: "dev_nlp_index_csid_"

      # [START proxy_container]
      - image: gcr.io/cloudsql-docker/gce-proxy:1.16
        name: cloudsql-proxy
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=leo-dataplatform:us-central1:leo-web-application-development=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-oauth-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-oauth-credentials
          secret:
            secretName: cloudsql-oauth-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir: {}
      # [END volumes]

---
# The hello service provides a load-balancing proxy over the hello-app
# pods. By specifying the type as a 'LoadBalancer', Kubernetes Engine will
# create an external HTTP load balancer.
apiVersion: v1
kind: Service
metadata:
  name: leo-backend-service
spec:
  type: LoadBalancer
  selector:
    app: leo-backend-service
  ports:
  - port: 80
    targetPort: 5000
